apiVersion: apps/v1
kind: Deployment
metadata:
  name: heatwave-frontend
  namespace: heatwave-ews
spec:
  replicas: 2
  selector:
    matchLabels: { app: heatwave-frontend }
  template:
    metadata:
      labels: { app: heatwave-frontend }
    spec:
      containers:
        - name: frontend
          image: heatwave-frontend:latest
          ports: [{ containerPort: 80 }]
